In [1]:
# Import Dependencies
import requests
import json
import os
import csv
from pathlib import Path
from pandas import DataFrame
from pandas.io.json import json_normalize
import pandas as pd
import numpy as np

In [2]:
# read json into dataframe
json_file = "la_meter_inventory.json"
la_meter_inventory_df = pd.read_json(json_file)
la_meter_inventory_df

,:@computed_region_2dna_qi2s,:@computed_region_k96s_3jcv,:@computed_region_kqwf_mjcx,:@computed_region_qz3q_ghft,:@computed_region_tatf_ua23,:@computed_region_ur2y_g4cx,blockface,latlng,metertype,parkingpolicy,raterange,ratetype,spaceid,stcl,timelimit
0,58.0,430.0,8.0,23445,456.0,16.0,4900 SUNSET BL,"{'latitude': '34.098024', 'longitude': '-118.2...",Single-Space,"TANS 4P-7P Mon-Fri | PKG 8A-4P Mon-Fri, 8A-8P Sat",$1.00,FLAT,VS336,NaN,2HR
1,76.0,703.0,9.0,23082,1018.0,NaN,700 E PICO BLVD,"{'latitude': '34.032054', 'longitude': '-118.2...",Single-Space,8A-6P Mon-Sat,$0.5 - $1,TOD,ED396,NaN,2HR
2,76.0,693.0,9.0,23076,1291.0,NaN,1300 S GRAND AVE,"{'latitude': '34.038125', 'longitude': '-118.2...",Single-Space,8A-8P Mon-Sat,$0.50,FLAT,CB211A,NaN,4HR
3,90.0,473.0,8.0,23444,1297.0,NaN,3100 SUNSET BL,"{'latitude': '34.084343', 'longitude': '-118.2...",Single-Space,8A-8P Mon-Sat,$1.00,FLAT,SL408,NaN,2HR
4,18.0,229.0,3.0,19733,288.0,NaN,7001 VAN NUYS BL,"{'latitude': '34.198035', 'longitude': '-118.4...",Single-Space,8A-8P Mon-Sat,$1.00,FLAT,VN1,NaN,2HR
5,82.0,414.0,8.0,23446,1303.0,NaN,1700 EL CERRITO PL,"{'latitude': '34.102349', 'longitude': '-118.3...",Single-Space,"TANS 8A-5A Fri | PKG 8A-8P Mon-Thu, 8A-12A Fri...",$1.5 - $3,TOD,HO1021A,12P-3P Mon,2HR
6,68.0,571.0,11.0,23078,628.0,NaN,800 BEACON AV,"{'latitude': '34.051792', 'longitude': '-118.2...",Single-Space,8A-6P Mon-Sat,$1.00,FLAT,WU759,12P-3P Thu,2HR
7,76.0,693.0,9.0,23076,1291.0,NaN,1301 S HOPE ST,"{'latitude': '34.039121', 'longitude': '-118.2...",Single-Space,8A-8P Mon-Sat,$1 - $2,TOD,CB118,NaN,4HR
8,26.0,629.0,6.0,23679,1095.0,NaN,8201 3RD ST,"{'latitude': '34.072672', 'longitude': '-118.3...",Single-Space,"8A-8P Mon-Sat, 11A-8P Sun",$1.00,FLAT,WF60,NaN,2HR
9,72.0,855.0,6.0,23443,748.0,9.0,1600 PONTIUS AV,"{'latitude': '34.04847', 'longitude': '-118.44...",Single-Space,8A-8P Mon-Sat,$1.00,FLAT,WS490,NaN,1HR
10,76.0,567.0,11.0,23078,847.0,54.0,600 BIXEL ST,"{'latitude': '34.052744', 'longitude': '-118.2...",Single-Space,8A-6P Mon-Sat,$1.00,FLAT,WU267,12P-3P Fri,2HR
11,50.0,867.0,10.0,24029,750.0,9.0,12300 OLYMPIC BL,"{'latitude': '34.031765', 'longitude': '-118.4...",Single-Space,8A-6P Mon-Sat,$1.00,FLAT,OS521,NaN,2HR
12,18.0,236.0,3.0,19729,290.0,NaN,14401 GILMORE ST,"{'latitude': '34.187711', 'longitude': '-118.4...",Single-Space,8A-8P Mon-Sat,$0.5 - $1,TOD,VN1001,10A-12P Mon,2HR
13,63.0,599.0,11.0,22722,1292.0,NaN,2900 8TH ST,"{'latitude': '34.057641', 'longitude': '-118.2...",Single-Space,8A-6P Mon-Sat,$1.00,FLAT,VW164,NaN,1HR
14,15.0,965.0,15.0,3350,1560.0,NaN,100 W. G ST,"{'latitude': '33.778415', 'longitude': '-118.2...",Single-Space,8A-6P Mon-Sat,$0.50,FLAT,WN281A,NaN,2HR
15,95.0,878.0,6.0,23451,749.0,NaN,9000 HARGIS ST,"{'latitude': '34.035939', 'longitude': '-118.3...",Single-Space,8A-8P Mon-Sat,$1.00,FLAT,RS106,8A-10A Tue,2HR
16,76.0,693.0,9.0,23076,1291.0,NaN,1400 S SANTEE ST,"{'latitude': '34.033455', 'longitude': '-118.2...",Single-Space,8A-6P Mon-Sat,$0.5 - $1,TOD,CB494,NaN,2HR
17,75.0,860.0,6.0,23443,736.0,9.0,2001 WESTWOOD BL,"{'latitude': '34.045973', 'longitude': '-118.4...",Single-Space,8A-8P Mon-Sat,$1.00,FLAT,WS278,NaN,1HR
18,76.0,693.0,9.0,23076,1291.0,NaN,300 E 16TH ST,"{'latitude': '34.032265', 'longitude': '-118.2...",Single-Space,TANS 4P-6P Mon-Fri | PKG 8A-4P Mon-Sat,$0.50,FLAT,CB4005,NaN,4HR
19,49.0,312.0,4.0,19346,1491.0,6.0,21101 VENTURA BL,"{'latitude': '34.16718', 'longitude': '-118.59...",Single-Space,8A-8P Mon-Sat,$1.00,FLAT,WH142,NaN,2HR
20,89.0,609.0,12.0,22726,638.0,NaN,600 OXFORD AV,"{'latitude': '34.06002', 'longitude': '-118.30...",Single-Space,8A-6P Mon-Sat,$1.00,FLAT,WW388,10A-1P Thu,1HR
21,28.0,533.0,9.0,22728,466.0,NaN,701 E 2ND ST,"{'latitude': '34.047225', 'longitude': '-118.2...",Single-Space,8A-8P Mon-Sat,$1.00,FLAT,AE155A,NaN,2HR
22,12.0,264.0,4.0,18909,578.0,NaN,18300 SHERMAN WAY,"{'latitude': '34.201022', 'longitude': '-118.5...",Single-Space,8A-8P Mon-Sat,$1.00,FLAT,R255,4A-630A Mon-Fri,2HR
23,89.0,584.0,12.0,22721,1294.0,16.0,3501 3RD ST,"{'latitude': '34.069142', 'longitude': '-118.2...",Single-Space,8A-6P Mon-Sat,$1.00,FLAT,VW966,NaN,1HR
24,89.0,596.0,12.0,23081,1294.0,NaN,300 S KENMORE AV,"{'latitude': '34.068738', 'longitude': '-118.2...",Single-Space,8A-6P Mon-Sat,$1.00,FLAT,VW1888,8A-10A Thu,2HR
25,34.0,423.0,8.0,23669,539.0,NaN,1100 VINE ST,"{'latitude': '34.09102', 'longitude': '-118.32...",Single-Space,8A-7P Mon-Sat,$1.00,FLAT,SH16,NaN,2HR
26,76.0,693.0,9.0,23076,1291.0,NaN,1301 S LOS ANGELES ST,"{'latitude': '34.035278', 'longitude': '-118.2...",Single-Space,8A-6P Mon-Sat,$0.5 - $1,TOD,CB389A,NaN,2HR
27,30.0,913.0,10.0,25074,1233.0,10.0,101 WASHINGTON BL (S),"{'latitude': '33.979971', 'longitude': '-118.4...",Single-Space,8A-6P Daily,$2.00,FLAT,WP13,730A-930A Tue,1HR
28,49.0,309.0,4.0,19347,1486.0,6.0,22100 CLARENDON ST,"{'latitude': '34.169592', 'longitude': '-118.6...",Single-Space,8A-8P Mon-Sat,$1.00,FLAT,WH277,4A-630A Fri,2HR
29,23.0,647.0,12.0,23080,1352.0,NaN,5061 PICO BL,"{'latitude': '34.048015', 'longitude': '-118.3...",Single-Space,8A-8P Mon-Sat,$1.00,FLAT,PB39,NaN,2HR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33959,72.0,854.0,6.0,23442,742.0,9.0,1400 WESTWOOD BL,"{'latitude': '34.055129', 'longitude': '-118.4...",Single-Space,10A-7P Mon-Sat,$1.00,FLAT,WS67,NaN,2HR
33960,28.0,540.0,11.0,22728,449.0,NaN,401 ALPINE ST,"{'latitude': '34.062669', 'longitude': '-118.2...",Single-Space,"TANS 7A-9A, 4P-6P Mon-Fri | PKG 9A-4P, 6P-8P M...",$0.5 - $4,TOD,CT216,NaN,2HR
33961,84.0,351.0,5.0,8492,1353.0,6.0,12001 VENTURA BL,"{'latitude': '34.143767', 'longitude': '-118.3...",Single-Space,8A-8P Mon-Sat,$1.00,FLAT,SC46,NaN,2HR
33962,50.0,865.0,10.0,23443,1380.0,9.0,11801 SANTA MONICA BL,"{'latitude': '34.042693', 'longitude': '-118.4...",Single-Space,"TANS 7A-9A, 4P-6P Mon-Fri | PKG 9A-4P, 6P-8P M...",$1.00,FLAT,SS227,NaN,1HR
33963,12.0,250.0,4.0,18909,308.0,NaN,7001 RESEDA BL,"{'latitude': '34.199063', 'longitude': '-118.5...",Single-Space,8A-8P Mon-Sat,$1.00,FLAT,R167,4A-630A Mon-Fri,2HR
33964,89.0,609.0,12.0,22723,647.0,NaN,3401 SAN MARINO ST,"{'latitude': '34.054505', 'longitude': '-118.3...",Single-Space,8A-6P Mon-Sat,$1.00,FLAT,WW2642,10A-1P Thu,2HR
33965,34.0,423.0,8.0,23669,539.0,NaN,6200 BANNER AV,"{'latitude': '34.09161', 'longitude': '-118.32...",Single-Space,8A-7P Mon-Sat,$1.00,FLAT,SH396A,10A-1P Tue,2HR
33966,76.0,542.0,9.0,23074,1502.0,NaN,400 MAIN ST,"{'latitude': '34.047053', 'longitude': '-118.2...",Single-Space,8A-8P Mon-Sat,$1 - $4,TOD,CB3730A,3A-5A Daily,2HR
33967,18.0,237.0,3.0,19729,1338.0,NaN,6300 SYLMAR AV,"{'latitude': '34.185097', 'longitude': '-118.4...",Single-Space,8A-6P Mon-Sat,$1.00,FLAT,VN722,NaN,2HR
33968,75.0,869.0,6.0,24029,814.0,9.0,10801 TENNESSEE AV,"{'latitude': '34.042632', 'longitude': '-118.4...",Single-Space,8A-6P Mon-Sat,$1.00,FLAT,PW134,8A-11A Thu,2HR
33969,26.0,462.0,6.0,23679,1082.0,NaN,401 FAIRFAX AV,"{'latitude': '34.079484', 'longitude': '-118.3...",Single-Space,"8A-8P Mon-Sat, 11A-8P Sun",$1.00,FLAT,BF33,NaN,2HR
33970,28.0,533.0,9.0,22728,466.0,NaN,401 N GAREY ST,"{'latitude': '34.051471', 'longitude': '-118.2...",Single-Space,6A-4P Mon-Fri,$1\hr - $4\10hr,JUMP,AE556,NaN,10HR
33971,36.0,970.0,15.0,3342,433.0,NaN,401 6TH ST,"{'latitude': '33.738699', 'longitude': '-118.2...",Single-Space,8A-6P Mon-Sat,$0.50,FLAT,SP568,4A-630A Thu,2HR
33972,13.0,209.0,5.0,8488,279.0,NaN,11000 MCCORMICK ST,"{'latitude': '34.165895', 'longitude': '-118.3...",Single-Space,8A-6P Mon-Sat,$1.00,FLAT,NH1118,10A-12P Fri,4HR
33973,89.0,591.0,12.0,22726,1261.0,NaN,601 ARDMORE AV,"{'latitude': '34.062643', 'longitude': '-118.3...",Single-Space,8A-6P Mon-Sat,$1.00,FLAT,WW873,8A-10A Thu,2HR
33974,18.0,237.0,3.0,19729,1338.0,NaN,6201 TYRONE AV,"{'latitude': '34.183633', 'longitude': '-118.4...",Single-Space,6A-4P Mon-Fri,$1\hr - $4\10hr,JUMP,VN674,NaN,10HR
33975,89.0,589.0,12.0,23081,879.0,NaN,401 S WESTERN AV,"{'latitude': '34.066409', 'longitude': '-118.3...",Single-Space,8A-6P Mon-Sat,$1.00,FLAT,WW315,NaN,1HR
33976,90.0,463.0,7.0,23670,1057.0,NaN,2700 ROWENA AV,"{'latitude': '34.107214', 'longitude': '-118.2...",Single-Space,8A-6P Mon-Sat,$1.00,FLAT,SL570,NaN,2HR
33977,64.0,417.0,8.0,23446,554.0,16.0,5601 HOLLYWOOD BL,"{'latitude': '34.101805', 'longitude': '-118.3...",Single-Space,8A-8P Mon-Sat,$1.00,FLAT,HW427,NaN,2HR
33978,95.0,873.0,6.0,23666,818.0,NaN,1101 BEVERLY DR,"{'latitude': '34.056786', 'longitude': '-118.3...",Single-Space,8A-6P Mon-Sat,$1.00,FLAT,PR374,10A-12P Mon,2HR
33979,83.0,331.0,7.0,19736,694.0,6.0,4300 ALLOTT AV,"{'latitude': '34.14784', 'longitude': '-118.42...",Single-Space,8A-8P Mon-Sat,$1.00,FLAT,SO907,8A-10A Thu,2HR
33980,76.0,547.0,9.0,23076,1050.0,NaN,501 W. OLYMPIC BL,"{'latitude': '34.043488', 'longitude': '-118.2...",Single-Space,"TANS 7A-10A, 3P-7P Mon-Fri | PKG 10A-3P Mon-Fr...",$0.5 - $2,TOD,CB4248,NaN,4HR
33981,34.0,424.0,8.0,23446,468.0,NaN,1401 IVAR AV,"{'latitude': '34.096773', 'longitude': '-118.3...",Single-Space,"8A-8P Mon-Sat, 11A-8P Sun",$0.5 - $1.5,TOD,SV291B,10A-1P Mon,2HR
33982,49.0,306.0,4.0,19346,1555.0,6.0,22700 VENTURA BL,"{'latitude': '34.166267', 'longitude': '-118.6...",Single-Space,8A-8P Mon-Sat,$1.00,FLAT,WH440,NaN,2HR
33983,82.0,415.0,8.0,23446,334.0,NaN,1700 WHITLEY AV,"{'latitude': '34.103015', 'longitude': '-118.3...",Single-Space,"8A-8P Mon-Thu, 8A-12A Fri-Sat, 11A-8P Sun",$1.5 - $3,TOD,HO958A,8A-10A Mon,2HR
33984,36.0,970.0,15.0,3342,433.0,NaN,300 7TH ST,"{'latitude': '33.737913', 'longitude': '-118.2...",Single-Space,8A-6P Mon-Sat,$0.50,FLAT,SP522,4A-630A Thu,2HR
33985,37.0,286.0,4.0,4278,1472.0,NaN,7101 OWENSMOUTH AV,"{'latitude': '34.200583', 'longitude': '-118.6...",Single-Space,8A-8P Mon-Sat,$1.00,FLAT,CP150,NaN,2HR
33986,28.0,540.0,11.0,22728,886.0,NaN,901 N. HILL ST,"{'latitude': '34.066378', 'longitude': '-118.2...",Single-Space,TANS 7A-9A Mon-Fri | PKG 9A-8P Mon-Sat,$0.5 - $3,TOD,CT299,4A-630A Thu,2HR
33987,26.0,635.0,7.0,23667,1293.0,NaN,700 DETROIT ST,"{'latitude': '34.06164', 'longitude': '-118.34...",Single-Space,8A-8P Mon-Sat,$1.00,FLAT,MM123,9A-11A Mon,2HR
33988,26.0,631.0,6.0,23679,1094.0,NaN,600 SAN VICENTE BL,"{'latitude': '34.06539', 'longitude': '-118.37...",Single-Space,"8A-8P Mon-Sat, 11A-8P Sun",$1.00,FLAT,WF434,12A-6A Wed,2HR

## Data Clean Up

##### Drop the following columns:
* :@computed_region_2dna_qi2s
* :@computed_region_k96s_3jcv
* :@computed_region_kqwf_mjcx
* :@computed_region_qz3q_ghft
* :@computed_region_tatf_ua23
* :@computed_region_ur2y_g4cx

In [3]:
la_meter_inventory_df.drop([':@computed_region_2dna_qi2s',
                            ':@computed_region_k96s_3jcv',
                            ':@computed_region_kqwf_mjcx',
                            ':@computed_region_qz3q_ghft',
                            ':@computed_region_tatf_ua23', 
                            ':@computed_region_ur2y_g4cx'], 
                           axis = 1, inplace = True)

In [15]:
la_meter_inventory_update_1 = pd.DataFrame(la_meter_inventory_df)
la_meter_inventory_update_1.head(5)

,blockface,latlng,metertype,parkingpolicy,raterange,ratetype,spaceid,stcl,timelimit
0,4900 SUNSET BL,"{'latitude': '34.098024', 'longitude': '-118.2...",Single-Space,"TANS 4P-7P Mon-Fri | PKG 8A-4P Mon-Fri, 8A-8P Sat",$1.00,FLAT,VS336,NaN,2HR
1,700 E PICO BLVD,"{'latitude': '34.032054', 'longitude': '-118.2...",Single-Space,8A-6P Mon-Sat,$0.5 - $1,TOD,ED396,NaN,2HR
2,1300 S GRAND AVE,"{'latitude': '34.038125', 'longitude': '-118.2...",Single-Space,8A-8P Mon-Sat,$0.50,FLAT,CB211A,NaN,4HR
3,3100 SUNSET BL,"{'latitude': '34.084343', 'longitude': '-118.2...",Single-Space,8A-8P Mon-Sat,$1.00,FLAT,SL408,NaN,2HR
4,7001 VAN NUYS BL,"{'latitude': '34.198035', 'longitude': '-118.4...",Single-Space,8A-8P Mon-Sat,$1.00,FLAT,VN1,NaN,2HR

In [16]:
# convert the dictionary in latlng column with latitude and longitude values to two different columns.
la_meter_inventory_update_1['latlng'].apply(pd.Series)

        latitude    longitude
0      34.098024  -118.296664
1      34.032054  -118.252521
2      34.038125  -118.264675
3      34.084343  -118.274463
4      34.198035   -118.44891
5      34.102349  -118.344672
6      34.051792   -118.27393
7      34.039121  -118.266015
8      34.072672  -118.369344
9       34.04847  -118.445724
10     34.052744  -118.262942
11     34.031765  -118.456463
12     34.187711  -118.447842
13     34.057641  -118.290637
14     33.778415  -118.263185
15     34.035939  -118.389367
16     34.033455  -118.259546
17     34.045973  -118.433669
18     34.032265  -118.260317
19      34.16718  -118.593401
20      34.06002  -118.307734
21     34.047225  -118.235352
22     34.201022  -118.533173
23     34.069142  -118.293717
24     34.068738  -118.296571
25      34.09102  -118.326508
26     34.035278  -118.259827
27     33.979971   -118.46549
28     34.169592  -118.608223
29     34.048015  -118.348314
...          ...          ...
33959  34.055129  -118.441449
33960  34.062669   -118.23909
33961  34.143767  -118.394157
33962  34.042693   -118.45875
33963  34.199063  -118.536168
33964  34.054505  -118.308507
33965   34.09161  -118.326018
33966  34.047053  -118.248087
33967  34.185097  -118.446469
33968  34.042632  -118.430166
33969  34.079484  -118.361557
33970  34.051471  -118.234389
33971  33.738699   -118.28658
33972  34.165895  -118.371686
33973  34.062643  -118.301672
33974  34.183633  -118.444448
33975  34.066409  -118.309207
33976  34.107214  -118.263742
33977  34.101805  -118.311946
33978  34.056786  -118.396607
33979   34.14784  -118.427891
33980  34.043488  -118.261168
33981  34.096773   -118.32889
33982  34.166267  -118.622105
33983  34.103015  -118.333267
33984  33.737913  -118.285211
33985  34.200583  -118.601673
33986  34.066378  -118.237841
33987   34.06164  -118.345289
33988   34.06539  -118.372585

[33989 rows x 2 columns]

In [17]:
# combine converted data with the rest of the dataframe
la_meter_inventory_update_2 = pd.concat([la_meter_inventory_updated.drop(['latlng'], axis=1), la_meter_inventory_updated['latlng'].apply(pd.Series)], axis=1)

In [18]:
la_meter_inventory_update_2.head()

,blockface,metertype,parkingpolicy,raterange,ratetype,spaceid,stcl,timelimit,latitude,longitude
0,4900 SUNSET BL,Single-Space,"TANS 4P-7P Mon-Fri | PKG 8A-4P Mon-Fri, 8A-8P Sat",$1.00,FLAT,VS336,NaN,2HR,34.098024,-118.296664
1,700 E PICO BLVD,Single-Space,8A-6P Mon-Sat,$0.5 - $1,TOD,ED396,NaN,2HR,34.032054,-118.252521
2,1300 S GRAND AVE,Single-Space,8A-8P Mon-Sat,$0.50,FLAT,CB211A,NaN,4HR,34.038125,-118.264675
3,3100 SUNSET BL,Single-Space,8A-8P Mon-Sat,$1.00,FLAT,SL408,NaN,2HR,34.084343,-118.274463
4,7001 VAN NUYS BL,Single-Space,8A-8P Mon-Sat,$1.00,FLAT,VN1,NaN,2HR,34.198035,-118.44891

In [24]:
# rename columns in the dataframe 
la_meter_inventory_update_2.rename(columns = 
                                   {"blockface": "address", 
                                    "metertype": "meter_type", 
                                    "parkingpolicy": "parking_policy", 
                                    "raterange": "rate_range", 
                                    "ratetype": "rate_type", 
                                    "spaceid": "id", 
                                    "stcl": "street_cleaning", 
                                    "timelimit": "parking_limit",}, 
                                   inplace=True)

In [25]:
la_meter_inventory_update_2.head()

,address,meter_type,parking_policy,rate_range,rate_type,id,street_cleaning,parking_limit,latitude,longitude
0,4900 SUNSET BL,Single-Space,"TANS 4P-7P Mon-Fri | PKG 8A-4P Mon-Fri, 8A-8P Sat",$1.00,FLAT,VS336,NaN,2HR,34.098024,-118.296664
1,700 E PICO BLVD,Single-Space,8A-6P Mon-Sat,$0.5 - $1,TOD,ED396,NaN,2HR,34.032054,-118.252521
2,1300 S GRAND AVE,Single-Space,8A-8P Mon-Sat,$0.50,FLAT,CB211A,NaN,4HR,34.038125,-118.264675
3,3100 SUNSET BL,Single-Space,8A-8P Mon-Sat,$1.00,FLAT,SL408,NaN,2HR,34.084343,-118.274463
4,7001 VAN NUYS BL,Single-Space,8A-8P Mon-Sat,$1.00,FLAT,VN1,NaN,2HR,34.198035,-118.44891

In [28]:
la_meter_inventory_update_2.groupby("meter_type")["meter_type"].count()

meter_type
Multi-Space       696
Single-Space    33293
Name: meter_type, dtype: int64

In [30]:
la_meter_inventory_update_2["parking_policy"].value_counts()

8A-8P Mon-Sat                                                                                        13070
8A-6P Mon-Sat                                                                                         8769
8A-8P Mon-Sat, 11A-8P Sun                                                                             2692
TANS 7A-9A, 4P-7P Mon-Fri | PKG 9A-4P Mon-Sat                                                          714
8A-8P Mon-Thu, 8A-12A Fri-Sat, 11A-8P Sun                                                              567
TANS 7A-9A, 4P-7P Mon-Fri | PKG 9A-4P Mon-Fri, 8A-8P Sat, 11A-8P Sun                                   562
TANS 7A-9A, 4P-7P Mon-Fri | PKG 9A-4P Mon-Fri, 8A-8P Sat                                               518
TANS 6A-9A Mon-Fri | PKG 9A-8P Mon-Sat                                                                 488
8A-6P Mon-Sat, 11A-6P Sun                                                                              485
TANS 4P-7P Mon-Fri | PKG 8A-4P Mon-Fri, 8A-8P Sat                                                      471
6A-4P Mon-Fri                                                                                          350
8A-6P Daily                                                                                            347
TANS 7A-9A Mon-Fri | PKG 9A-6P Mon-Sat                                                                 334
TANS 7A-9A, 4P-6P Mon-Fri | PKG 9A-4P, 6P-8P Mon-Fri, 8A-8P Sat                                        286
8A-6P Mon-Fri                                                                                          256
TANS 4P-6P Mon-Fri | PKG 8A-4P Mon-Sat                                                                 220
8A-7P Mon-Sat                                                                                          219
TANS 4P-7P Mon-Fri | PKG 8A-4P Mon-Sat                                                                 192
TANS 7A-9A, 4P-6P Mon-Fri | PKG 9A-4P Mon-Sat                                                          172
8A-9P Mon-Sat                                                                                          160
TANS 4P-6P Mon-Fri | PKG 8A-4P, 6P-8P Mon-Fri, 8A-8P Sat                                               147
TANS 7A-9A Mon-Fri | PKG 9A-8P Mon-Sat                                                                 147
TANS 7A-9A, 3P-7P Mon-Fri | PKG 9A-3P Mon-Fri, 8A-8P Sat                                               146
TANS 7A-9A, 4P-7P Mon-Fri | PKG 9A-4P, 7P-9P Mon-Fri, 8A-9P Sat                                        135
8A-8P Mon-Thu, 8A-10P Fri-Sat, 11A-8P Sun                                                              118
8A-12A Daily                                                                                           110
TANP 3A-6A | PKG 8A-8P Mon-Thu, 8A-12A Fri-Sat, 11A-8P Sun                                             107
TANS 7A-9A, 3P-7P Mon-Fri | PKG 9A-3P Mon-Sat                                                          101
PKG 8A-6P Mon-Sat | NP 7P-7A Nightly                                                                    93
TANS 6A-9A, 330P-7P Mon-Fri | PKG 9A-330P Mon-Fri, 8A-8P Sat                                            79
                                                                                                     ...
PKG 8A-6P Daily | PLO 6P-12A Daily                                                                       2
PLO  5P-12A Mon-Fri, 8A-12A Sat-Sun | PKG 8A-5P Mon-Fri                                                  2
CLO 8A-2P Mon-Fri | PKG 2P-8P Mon-Fri, 8A-8P Sat                                                         2
PKG 8A-6P Mon-Sat, 11A-6P Sun | TAXI 6P-3A Next Day Mon-Sat                                              2
TANS 8A-10A, 2P-4P Mon-Fri | PKG 10A-2P, 4P-6P Mon-Fri, 8A-6P Sat                                        2
TANS 7A-9A, 4P-7P Mon-Fri | PKG 9A-4P Mon-Fri, 8A-7P Sat                                                 2
TANS 6A-9A, 330P-7P Mon-Fri | PKG 9A-330P Mon-Fri, 8A-6P Sat | PLO 7P-12A Mon-Fri, 6P-12A Sat-Sun        2
PKG 8A-6P Mon-Sat, 11A-6P Sun | TAXI 6P-3A Nightly                                                       2
PLO 8A-6P Mon-Sat | PKG 6P-8P Mon-Sat, 11A-8P Sun                                                        2
PLO 10A-3P, 6P-12A Daily | PKG 8A-10A Mon-Sat, 3P-6P Daily                                               2
PKG 8A-6P Mon-Sat | PLO 6P-2A Nightly | NP 2A-5A Daily                                                   2
PKG 9A-4P Mon-Sat | CLO 7A-9A, 4P-6P Mon-Fri                                                             2
PKG 8A-6P Mon-Sat, 11A-6P Sun | NP 6P-12A Daily                                                          2
PKG 8A-6P Mon-Sat, 11A-6P Sun | NP 6P-6A Nightly                                                         2
PLO 10A-4P Mon-Sat | PKG 8A-10A, 4P-8P Mon-Sat | TANP 6A-3P Sun                                          2
TANS 6A-9A, 4P-7P Daily | PKG 9A-4P Mon-Sat                                                              2
TANS 4P-7P Mon-Fri | PKG 8A-4P Mon-Sat | PLO 7P-12A Daily                                                2
TANS 3P-7P Mon-Fri | PKG 8A-3P Mon-Sat                                                                   2
TANS 7A-9A Mon-Fri | PKG 9A-6P Mon-Sat | PLO 6P-2A Nightly                                               2
TANS 7A-9A, 3P-7P Mon-Fri | PKG 9A-3P Mon-Fri, 8A-7P Sat | PLO 7P-2A Nightly                             2
TANS 7A-9A, 4P-6P Mon-Fri | PKG 9A-4P Mon-Fri, 8A-6P Sat | TANP 6P-2A Next Dat Nightly                   2
TANS 7A-9A Mon-Fri | PKG 9A-6P Mon-Sat, 11A-6P Sun | PLO 6P-12A Daily                                    1
PLO All Day Fri-Sat | PKG 8A-8P Mon-Thu                                                                  1
TANP 6P-6A | PKG 8A-6P Mon-Sat, 11A-6P Sun                                                               1
8A-6P Mon-Sat | PLO 6P-12A Daily                                                                         1
PKG 8A-6P Mon-Sat | NP Tue 12A-630A; Sun; Mon & Wed-Sat 12A-6A; Daily 9P-12A                             1
PKG 8A-11P Mon-Sat | NP 11P-8A Nightly                                                                   1
8A-9P Daily                                                                                              1
PKG 10A-6P Mon-Fri, 10A-7P Sat | PLO 6P-9P Mon-Fri                                                       1
CLO 7A-6P Mon-Sat | PKG 6P-8P Mon-Sat, 11A-8P Sun                                                        1
Name: parking_policy, Length: 177, dtype: int64

In [31]:
la_meter_inventory_update_2["rate_type"].value_counts()

FLAT        27151
TOD          5347
JUMP         1391
SEASONAL      100
Name: rate_type, dtype: int64

In [32]:
la_meter_inventory_update_2["parking_limit"].value_counts()

2HR      21022
1HR       7200
4HR       3611
10HR      1155
30MIN      439
15MIN      326
6HR        236
Name: parking_limit, dtype: int64

In [33]:
la_meter_inventory_update_2["street_cleaning"].value_counts()

8A-10A Mon         624
8A-10A Thu         618
8A-10A Tue         564
12P-3P Thu         470
10A-12P Fri        454
8A-10A Fri         442
4A-630A Thu        389
4A-630A Fri        357
12P-3P Fri         355
10A-12P Mon        349
10A-12P Thu        326
8A-10A Wed         307
4A-630A Wed        272
10A-12P Tue        254
12P-3P Tue         239
4A-630A Mon-Fri    232
10A-12P Wed        226
12P-3P Mon         217
10A-1P Thu         212
10A-1P Wed         179
10A-1P Mon         176
11A-2P Wed         143
1A-4A Fri          132
10A-1P Tue         118
8A-11A Wed         108
1A-4A Wed           98
730A-930A Mon       86
8A-11A Fri          84
4A-630A Tue         79
12P-2P Fri          78
                  ...
12P-2P Wed          32
12A-6A Wed          31
12P-2P Mon          30
1230P-230P Wed      30
9A-11A Wed          30
9A-12P Fri          29
12P-2P Tue          29
12P-230P Tue        21
730A-930A Wed       19
12P-230P Mon        18
1230P-230P Tue      18
730A-1030A Tue      18
8A-11A Mon          17
9A-11A Thu          16
11A-1P Wed          16
11A-1P Mon          14
12P-230P Thu        14
9A-10A Mon          12
11A-1P Thu          11
10A-1P Fri          10
1A-6A Tue           10
730A-930A Fri        9
830A-1030A Mon       9
4A-7A Fri            8
9A-10A Fri           7
730A-1030A Wed       7
11A-130P Tue         5
830A-1030A Tue       4
1130A-130P Tue       4
12A-6A Fri           2
Name: street_cleaning, Length: 79, dtype: int64

In [34]:
la_meter_inventory_update_2.to_csv("la_meter_inventory_final.csv", encoding = 'utf-8', index = False)