In [1]:
# import dependencies
import json
import os
import csv
from pandas import DataFrame
import pandas as pd
import numpy as np
from datetime import datetime
import datetime as dt
import time
import shutil
import fnmatch
from pyproj import Proj, transform

In [47]:
# create working directories for your data 
def work_dir():
    working_directory = os.getcwd()
    folders = ["data/missed_lat_long_db_ready", "data/citations_db_ready", "data/api_responses/processed"]
    for folder in folders:
        try:
            os.makedirs(os.path.join(working_directory, folder))
        except OSError:
            print ("Creation of working directories failed/directory exists")
        else:
            print ("Successfully created "f"{folder}")
        
    print("========================================================")

work_dir()

Successfully created data/missed_lat_long_db_ready
Successfully created data/citations_db_ready
Successfully created data/api_responses/processed
========================================================

In [13]:
files=[]
for file in os.listdir('data/api_responses/'):
    if fnmatch.fnmatch(file, '*.json'):
        files.append(file)
print(files)

['0000000002.json', '0000000003.json', '0000000004.json', '0000000005.json', '0000000006.json', '0000000007.json', '0000000008.json', '0000000009.json', '0000000010.json', '0000000011.json', '0000000012.json', '0000000013.json', '0000000014.json', '0000000015.json', '0000000016.json', '0000000017.json', '0000000018.json', '0000000019.json', '0000000020.json']

In [14]:
data_list = []
for f in files[0:1]:
    filename = 'data/api_responses/'+f
    with open(filename) as json_file:  
        data = json.load(json_file)
        for s in data:
            data_list.append(s)
    shutil.move('data/api_responses/'+f, 'data/api_responses/processed/'+f)
    print(f"{f} --> moved to processed directory")

transformed_df = pd.DataFrame(data_list)
transformed_df

0000000002.json --> moved to processed directory

,agency,body_style,color,fine_amount,issue_date,issue_time,latitude,location,longitude,make,marked_time,meter_id,plate_expiry_date,route,rp_state_plate,ticket_number,vin,violation_code,violation_description
0,54,PA,GY,73,2016-03-14T00:00:00.000,825,6449934.4,104 HARPER AVE S,1849603.2,AUDI,NaN,NaN,11,00474,CA,4278367181,NaN,80.69BS,NO PARK/STREET CLEAN
1,54,PA,GN,73,2016-03-14T00:00:00.000,827,6449934.4,112 HARPER AVE S,1849577.9,TOYT,NaN,NaN,3,00474,CA,4278367192,NaN,80.69BS,NO PARK/STREET CLEAN
2,54,PA,BK,73,2016-03-14T00:00:00.000,830,6449934,150 HARPER AVE S,1849457.5,LEXS,NaN,NaN,5,00474,CA,4278367203,NaN,80.69BS,NO PARK/STREET CLEAN
3,54,PA,BK,73,2016-03-14T00:00:00.000,831,6449934,150 HARPER AVE S,1849457.5,VOLK,NaN,NaN,6,00474,CA,4278367214,NaN,80.69BS,NO PARK/STREET CLEAN
4,54,PA,GY,73,2016-03-14T00:00:00.000,833,6449934,150 HARPER AVE S,1849457.5,AUDI,NaN,NaN,10,00474,CA,4278367225,NaN,80.69BS,NO PARK/STREET CLEAN
5,54,PA,BK,73,2016-03-14T00:00:00.000,906,6448645.8,320 ORLANDO AVE S,1849022.5,ACUR,NaN,NaN,7,00474,CA,4278367236,NaN,80.69BS,NO PARK/STREET CLEAN
6,54,PA,SL,73,2016-03-14T00:00:00.000,907,6448645.8,320 ORLANDO AVE S,1849022.5,HOND,NaN,NaN,5,00474,IL,4278367240,NaN,80.69BS,NO PARK/STREET CLEAN
7,54,PA,WT,73,2016-03-14T00:00:00.000,910,6449559.8,361 SWEETZER AVE S,1848631.4,MERZ,NaN,NaN,NaN,00474,CA,4278367251,NaN,80.69BS,NO PARK/STREET CLEAN
8,54,PA,BK,73,2016-03-14T00:00:00.000,912,99999,8250 W BLACKBURN AVE,99999,TOYT,NaN,NaN,6,00474,CA,4278367262,NaN,80.69BS,NO PARK/STREET CLEAN
9,54,PA,GY,73,2016-03-14T00:00:00.000,916,6450240.8,316 LA JOLLA AVE S,1850396.6,HOND,NaN,NaN,11,00474,CA,4278367273,NaN,80.69BS,NO PARK/STREET CLEAN
10,54,TK,WT,73,2016-03-14T00:00:00.000,918,99999,306 LA JOLLA AVE S,99999,FORD,NaN,NaN,7,00474,CA,4278367284,NaN,80.69BS,NO PARK/STREET CLEAN
11,54,PA,BK,73,2016-03-14T00:00:00.000,921,6450636.4,8142 W BLACKBURN AVE,1848545.4,MAZD,NaN,NaN,12,00474,CA,4278367295,NaN,80.69BS,NO PARK/STREET CLEAN
12,54,PA,GY,73,2016-03-14T00:00:00.000,925,99999,8321 4TH ST W,99999,SUBA,NaN,NaN,4,00474,CA,4278367306,NaN,80.69BS,NO PARK/STREET CLEAN
13,54,PA,GY,73,2016-03-14T00:00:00.000,928,99999,8449 4TH ST W,99999,PONT,NaN,NaN,5,00474,CA,4278367310,NaN,80.69BS,NO PARK/STREET CLEAN
14,54,PA,BK,73,2016-03-14T00:00:00.000,931,99999,6650 COLGATE AVE W,99999,BENT,NaN,NaN,6,00474,MT,4278367321,NaN,80.69BS,NO PARK/STREET CLEAN
15,54,PA,GY,73,2016-03-14T00:00:00.000,935,6449795,6566 COLGATE AVE W,1848047,TOYT,NaN,NaN,2,00474,CA,4278367332,NaN,80.69BS,NO PARK/STREET CLEAN
16,54,PA,GY,25,2016-03-14T00:00:00.000,936,6449795,6566 COLGATE AVE W,1848047,TOYT,NaN,NaN,2,00474,CA,4278367343,NaN,5200,DISPLAY OF PLATES
17,54,PA,SL,73,2016-03-14T00:00:00.000,938,6449892.1,6556 COLGATE AVE W,1848033.5,CHRY,NaN,NaN,3,00474,AZ,4278367354,NaN,80.69BS,NO PARK/STREET CLEAN
18,54,PA,RD,73,2016-03-14T00:00:00.000,939,6449989.1,6546 COLGATE AVE W,1848020,CHEV,NaN,NaN,1,00474,OH,4278367365,NaN,80.69BS,NO PARK/STREET CLEAN
19,54,PA,SL,73,2016-03-14T00:00:00.000,947,99999,6516 5TH ST W,99999,LEXS,NaN,NaN,12,00474,CA,4278367376,NaN,80.69BS,NO PARK/STREET CLEAN
20,54,PA,PR,73,2016-03-14T00:00:00.000,952,6448748.6,6670 LINDENHURST AVE W,1846980.6,HOND,NaN,NaN,8,00474,CA,4278367380,NaN,80.69BS,NO PARK/STREET CLEAN
21,54,PA,BK,73,2016-03-14T00:00:00.000,954,6448748.6,6670 LINDENHURST AVE W,1846980.6,HYUN,NaN,NaN,7,00474,CA,4278367391,NaN,80.69BS,NO PARK/STREET CLEAN
22,54,PA,GY,73,2016-03-14T00:00:00.000,955,6448748.6,6670 LINDENHURST AVE W,1846980.6,TOYT,NaN,NaN,1,00474,CA,4278367402,NaN,80.69BS,NO PARK/STREET CLEAN
23,54,PA,GY,25,2016-03-14T00:00:00.000,956,6448748.6,6670 LINDENHURST AVE W,1846980.6,TOYT,NaN,NaN,1,00474,CA,4278367413,NaN,5204A-,DISPLAY OF TABS
24,54,PA,RD,73,2016-03-14T00:00:00.000,1001,99999,6241 W MARYLAND DR,99999,HOND,NaN,NaN,12,00474,CA,4278367424,NaN,80.69BS,NO PARK/STREET CLEAN
25,54,PA,GY,73,2016-03-14T00:00:00.000,1006,99999,6241 DREXEL AVE W,99999,LEXS,NaN,NaN,2,00474,CA,4278367435,NaN,80.69BS,NO PARK/STREET CLEAN
26,54,PA,MR,73,2016-03-14T00:00:00.000,1217,6462773,5900 W WARING AVE,1853584.1,KIA,NaN,NaN,6,00474,CA,4278367446,NaN,80.69BS,NO PARK/STREET CLEAN
27,54,PA,WT,73,2016-03-14T00:00:00.000,1222,99999,749 N LILLIAN WAY,99999,VOLV,NaN,NaN,6,00474,CA,4278367450,NaN,80.69BS,NO PARK/STREET CLEAN
28,54,PA,BK,73,2016-03-14T00:00:00.000,1224,6462437.6,727 N LILLIAN WAY,1853099.8,HOND,NaN,NaN,9,00474,CA,4278367461,NaN,80.69BS,NO PARK/STREET CLEAN
29,54,PA,BK,25,2016-03-14T00:00:00.000,1225,6462437.6,727 N LILLIAN WAY,1853099.8,HOND,NaN,NaN,9,00474,CA,4278367472,NaN,5204A-,DISPLAY OF TABS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499970,56,TK,BN,93,2015-01-16T00:00:00.000,1137,6410887.7,744 12TH ST,1834090.7,FRHT,NaN,NaN,9,00600,CA,4250685434,NaN,80.56E4+,RED ZONE
499971,56,PA,GY,58,2015-01-16T00:00:00.000,1247,6479980.6,1224 OLYMPIC BLVD,1839651.3,FORD,1130,NaN,201504,00600,CA,4250685445,NaN,80.69C,PARKED OVER TIME LIM
499972,56,PA,BK,58,2015-01-16T00:00:00.000,1252,6416051.1,1400 OLYMPIC BLVD,1829910.4,LEXS,1130,NaN,201504,00600,CA,4250685456,NaN,80.69C,PARKED OVER TIME LIM
499973,56,PA,BK,58,2015-01-16T00:00:00.000,1259,6415496.3,1211 OLYMPIC BLVD,1829372,FORD,1130,NaN,201509,00600,CA,4250685460,NaN,80.69C,PARKED OVER TIME LIM
499974,56,PA,BK,63,2015-01-16T00:00:00.000,1312,6484927.7,701 12TH ST E,1834742.1,NISS,NaN,ED219,201504,00600,CA,4250685471,NaN,88.13B+,METER EXP.
499975,56,PA,GY,63,2015-01-16T00:00:00.000,1506,6502799,201 12TH ST W,1742891.1,LINC,NaN,CB4319,201504,00600,CA,4250685493,NaN,88.13B+,METER EXP.
499976,56,PA,GY,63,2015-01-16T00:00:00.000,1515,6504124.6,300 14TH ST E,1743768.1,FORD,NaN,CB2049,201502,00600,CA,4250685504,NaN,88.13B+,METER EXP.
499977,56,PA,GY,63,2015-01-16T00:00:00.000,1521,6482449.1,1401 MAIN ST S,1835213.1,LEXS,NaN,CB348,NaN,00600,CA,4250685515,NaN,88.13B+,METER EXP.
499978,56,PA,GY,63,2015-01-16T00:00:00.000,1534,6485961.1,900 12TH ST E,1834155.2,TOYT,NaN,ED279,201502,00600,CA,4250685526,NaN,88.13B+,METER EXP.
499979,56,PA,GY,63,2015-01-16T00:00:00.000,1558,6487821.1,301 WALL ST S,1839930.1,NISS,NaN,LT302,201503,00600,CA,4250685530,NaN,88.13B+,METER EXP.
499980,56,TK,WT,68,2015-01-16T00:00:00.000,1605,6417115.2,843 MAPLE ST,1825539.9,GRUM,NaN,NaN,201503,00600,CA,4250685541,NaN,22500H,DOUBLE PARKING
499981,56,TK,BN,93,2015-01-16T00:00:00.000,1608,6414698.9,950 OLYMPIC BLVD,1828648,FRHT,NaN,NaN,9,00600,CA,4250685552,NaN,80.69AP+,NO STOP/STANDING
499982,56,PA,BK,63,2015-01-16T00:00:00.000,1613,6483701.7,1201 SANTEE ST S,1835694,CADI,NaN,CB839,201507,00600,CA,4250685563,NaN,88.13B+,METER EXP.
499983,56,PA,BK,63,2015-01-16T00:00:00.000,1711,6458410,1400 MAPLE AVE S,1762259.9,HOND,NaN,CB2075,201503,00600,CA,4250685574,NaN,88.13B+,METER EXP.
499984,56,PA,BL,58,2015-01-16T00:00:00.000,1716,6485354.6,900 WALL ST S,1836571.8,TOYT,NaN,CB637,201503,00600,CA,4250685585,NaN,88.03A,OUTSIDE LINES/METER
499985,56,CM,WT,93,2015-01-02T00:00:00.000,1259,99999,1438 EASTLAKE AVE,99999,FORD,NaN,NaN,NaN,00632,CA,4250686016,NaN,80.56E4+,RED ZONE
499986,56,PA,GN,25,2015-01-02T00:00:00.000,1318,99999,2007 N ALTA ST,99999,TOYT,NaN,NaN,201410,00632,CA,4250686020,NaN,5204A-,DISPLAY OF TABS
499987,56,PA,SL,63,2015-01-02T00:00:00.000,1441,6498857.8,1300 BIGGY ST,1844506.4,HOND,NaN,MD322,201504,00632,CA,4250686031,NaN,88.13B+,METER EXP.
499988,56,PA,WT,93,2015-01-02T00:00:00.000,1505,6490237.8,200 COLLEGE ST W,1845602.8,HOND,NaN,NaN,201511,00632,CA,4250686042,NaN,80.69A+,STOP/STAND PROHIBIT
499989,56,PA,WT,25,2015-01-02T00:00:00.000,1505,6490237.8,200 COLLEGE ST W,1845602.8,HOND,NaN,NaN,201511,00632,CA,4250686053,NaN,5200,DISPLAY OF PLATES
499990,56,PA,BK,25,2015-01-02T00:00:00.000,1516,6491170.5,901 AVILA ST,1843215.5,CHRY,NaN,NaN,201401,00632,CA,4250686064,NaN,5204A-,DISPLAY OF TABS
499991,56,CM,BN,93,2015-01-02T00:00:00.000,1549,6490797.9,1261 PALMETTO ST,1837139,OTHR,NaN,NaN,11,00632,CA,4250686075,NaN,80.56E4+,RED ZONE
499992,56,PA,WT,58,2015-01-02T00:00:00.000,1623,6498857.8,1300 BIGGY ST,1844506.4,NISS,NaN,MD319,201509,00632,CA,4250686086,NaN,88.03A,OUTSIDE LINES/METER
499993,56,PA,SL,93,2015-01-02T00:00:00.000,1645,6495106.6,325 BOYLE AVE S,1838751.6,FORD,NaN,NaN,201510,00632,CA,4250686090,NaN,80.56E4+,RED ZONE
499994,56,PA,BK,63,2015-01-05T00:00:00.000,1316,6524824,821 MAPLE AVE S,1822642.1,TOYT,NaN,CB717,201509,00681,CA,4250686425,NaN,88.13B+,METER EXP.
499995,56,PA,GY,63,2015-01-05T00:00:00.000,1336,6640079.3,951 TOWNE AVE S,1841186.2,TOYT,NaN,ED651A,NaN,00681,CA,4250686436,NaN,88.13B+,METER EXP.
499996,56,PA,GY,63,2015-01-05T00:00:00.000,1340,6505990.5,777 10TH ST E,1741998.2,CHEV,NaN,ED658,201512,00681,CA,4250686440,NaN,88.13B+,METER EXP.
499997,56,PA,RD,63,2015-01-05T00:00:00.000,1349,6484589.5,1122 WALL ST S,1835634.7,HOND,NaN,CB2180A,201508,00681,CA,4250686451,NaN,88.13B+,METER EXP.
499998,56,PA,BK,58,2015-01-05T00:00:00.000,1352,6484302.6,1202 WALL ST S,1835206.4,PONT,NaN,CB2162,201302,00681,CA,4250686462,NaN,88.03A,OUTSIDE LINES/METER
499999,56,PA,BK,25,2015-01-05T00:00:00.000,1354,6484302.6,1202 WALL ST S,1835206.4,PONT,NaN,NaN,201302,00681,CA,4250686473,NaN,5204A-,DISPLAY OF TABS

In [15]:
# preview the missing values and the % of missing values in each column
df = transformed_df
def missing_values_table(df):
        mis_val = df.isnull().sum()
        mis_val_percent = 100 * df.isnull().sum() / len(df)
        mis_val_table = pd.concat([mis_val, mis_val_percent], axis=1)
        mis_val_table_ren_columns = mis_val_table.rename(
        columns = {0 : 'Missing Values', 1 : '% of Total Values'})
        mis_val_table_ren_columns = mis_val_table_ren_columns[
            mis_val_table_ren_columns.iloc[:,1] != 0].sort_values(
        '% of Total Values', ascending=False).round(1)
        print ("Selected dataframe has " + str(df.shape[1]) + " columns.\n"      
            "There are " + str(mis_val_table_ren_columns.shape[0]) +
              " columns that have missing values.")
        return mis_val_table_ren_columns

missing_values_table(df)

Selected dataframe has 19 columns.
There are 15 columns that have missing values.

                       Missing Values  % of Total Values
vin                            483691               96.7
marked_time                    480846               96.2
meter_id                       365811               73.2
plate_expiry_date               44052                8.8
route                            2697                0.5
body_style                        414                0.1
make                              398                0.1
fine_amount                       225                0.0
color                             197                0.0
issue_time                        157                0.0
location                           76                0.0
agency                             64                0.0
issue_date                         64                0.0
rp_state_plate                     56                0.0
violation_description              36                0.0

In [16]:
transformed_df.drop(
    [
#     "vin",
     "marked_time",
     "plate_expiry_date",
     "rp_state_plate"],
    axis = 1, inplace = True)

In [17]:
def time_date_transformation():
    
    # transform "issue_date" to a date/time format
    transformed_df['issue_date'] = pd.to_datetime(transformed_df['issue_date'], dayfirst=True)
    
    # add zeros to time where it is missing
    transformed_df['issue_time'] = transformed_df['issue_time'].str.rjust(4, "0")
    
    # transform values in "issue_time" column to date time format
    transformed_df['issue_time'] = pd.to_datetime(transformed_df['issue_time'],format ='%H%M').dt.time
    
    return transformed_df

time_date_transformation()

,agency,body_style,color,fine_amount,issue_date,issue_time,latitude,location,longitude,make,meter_id,route,ticket_number,vin,violation_code,violation_description
0,54,PA,GY,73,2016-03-14,08:25:00,6449934.4,104 HARPER AVE S,1849603.2,AUDI,NaN,00474,4278367181,NaN,80.69BS,NO PARK/STREET CLEAN
1,54,PA,GN,73,2016-03-14,08:27:00,6449934.4,112 HARPER AVE S,1849577.9,TOYT,NaN,00474,4278367192,NaN,80.69BS,NO PARK/STREET CLEAN
2,54,PA,BK,73,2016-03-14,08:30:00,6449934,150 HARPER AVE S,1849457.5,LEXS,NaN,00474,4278367203,NaN,80.69BS,NO PARK/STREET CLEAN
3,54,PA,BK,73,2016-03-14,08:31:00,6449934,150 HARPER AVE S,1849457.5,VOLK,NaN,00474,4278367214,NaN,80.69BS,NO PARK/STREET CLEAN
4,54,PA,GY,73,2016-03-14,08:33:00,6449934,150 HARPER AVE S,1849457.5,AUDI,NaN,00474,4278367225,NaN,80.69BS,NO PARK/STREET CLEAN
5,54,PA,BK,73,2016-03-14,09:06:00,6448645.8,320 ORLANDO AVE S,1849022.5,ACUR,NaN,00474,4278367236,NaN,80.69BS,NO PARK/STREET CLEAN
6,54,PA,SL,73,2016-03-14,09:07:00,6448645.8,320 ORLANDO AVE S,1849022.5,HOND,NaN,00474,4278367240,NaN,80.69BS,NO PARK/STREET CLEAN
7,54,PA,WT,73,2016-03-14,09:10:00,6449559.8,361 SWEETZER AVE S,1848631.4,MERZ,NaN,00474,4278367251,NaN,80.69BS,NO PARK/STREET CLEAN
8,54,PA,BK,73,2016-03-14,09:12:00,99999,8250 W BLACKBURN AVE,99999,TOYT,NaN,00474,4278367262,NaN,80.69BS,NO PARK/STREET CLEAN
9,54,PA,GY,73,2016-03-14,09:16:00,6450240.8,316 LA JOLLA AVE S,1850396.6,HOND,NaN,00474,4278367273,NaN,80.69BS,NO PARK/STREET CLEAN
10,54,TK,WT,73,2016-03-14,09:18:00,99999,306 LA JOLLA AVE S,99999,FORD,NaN,00474,4278367284,NaN,80.69BS,NO PARK/STREET CLEAN
11,54,PA,BK,73,2016-03-14,09:21:00,6450636.4,8142 W BLACKBURN AVE,1848545.4,MAZD,NaN,00474,4278367295,NaN,80.69BS,NO PARK/STREET CLEAN
12,54,PA,GY,73,2016-03-14,09:25:00,99999,8321 4TH ST W,99999,SUBA,NaN,00474,4278367306,NaN,80.69BS,NO PARK/STREET CLEAN
13,54,PA,GY,73,2016-03-14,09:28:00,99999,8449 4TH ST W,99999,PONT,NaN,00474,4278367310,NaN,80.69BS,NO PARK/STREET CLEAN
14,54,PA,BK,73,2016-03-14,09:31:00,99999,6650 COLGATE AVE W,99999,BENT,NaN,00474,4278367321,NaN,80.69BS,NO PARK/STREET CLEAN
15,54,PA,GY,73,2016-03-14,09:35:00,6449795,6566 COLGATE AVE W,1848047,TOYT,NaN,00474,4278367332,NaN,80.69BS,NO PARK/STREET CLEAN
16,54,PA,GY,25,2016-03-14,09:36:00,6449795,6566 COLGATE AVE W,1848047,TOYT,NaN,00474,4278367343,NaN,5200,DISPLAY OF PLATES
17,54,PA,SL,73,2016-03-14,09:38:00,6449892.1,6556 COLGATE AVE W,1848033.5,CHRY,NaN,00474,4278367354,NaN,80.69BS,NO PARK/STREET CLEAN
18,54,PA,RD,73,2016-03-14,09:39:00,6449989.1,6546 COLGATE AVE W,1848020,CHEV,NaN,00474,4278367365,NaN,80.69BS,NO PARK/STREET CLEAN
19,54,PA,SL,73,2016-03-14,09:47:00,99999,6516 5TH ST W,99999,LEXS,NaN,00474,4278367376,NaN,80.69BS,NO PARK/STREET CLEAN
20,54,PA,PR,73,2016-03-14,09:52:00,6448748.6,6670 LINDENHURST AVE W,1846980.6,HOND,NaN,00474,4278367380,NaN,80.69BS,NO PARK/STREET CLEAN
21,54,PA,BK,73,2016-03-14,09:54:00,6448748.6,6670 LINDENHURST AVE W,1846980.6,HYUN,NaN,00474,4278367391,NaN,80.69BS,NO PARK/STREET CLEAN
22,54,PA,GY,73,2016-03-14,09:55:00,6448748.6,6670 LINDENHURST AVE W,1846980.6,TOYT,NaN,00474,4278367402,NaN,80.69BS,NO PARK/STREET CLEAN
23,54,PA,GY,25,2016-03-14,09:56:00,6448748.6,6670 LINDENHURST AVE W,1846980.6,TOYT,NaN,00474,4278367413,NaN,5204A-,DISPLAY OF TABS
24,54,PA,RD,73,2016-03-14,10:01:00,99999,6241 W MARYLAND DR,99999,HOND,NaN,00474,4278367424,NaN,80.69BS,NO PARK/STREET CLEAN
25,54,PA,GY,73,2016-03-14,10:06:00,99999,6241 DREXEL AVE W,99999,LEXS,NaN,00474,4278367435,NaN,80.69BS,NO PARK/STREET CLEAN
26,54,PA,MR,73,2016-03-14,12:17:00,6462773,5900 W WARING AVE,1853584.1,KIA,NaN,00474,4278367446,NaN,80.69BS,NO PARK/STREET CLEAN
27,54,PA,WT,73,2016-03-14,12:22:00,99999,749 N LILLIAN WAY,99999,VOLV,NaN,00474,4278367450,NaN,80.69BS,NO PARK/STREET CLEAN
28,54,PA,BK,73,2016-03-14,12:24:00,6462437.6,727 N LILLIAN WAY,1853099.8,HOND,NaN,00474,4278367461,NaN,80.69BS,NO PARK/STREET CLEAN
29,54,PA,BK,25,2016-03-14,12:25:00,6462437.6,727 N LILLIAN WAY,1853099.8,HOND,NaN,00474,4278367472,NaN,5204A-,DISPLAY OF TABS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499970,56,TK,BN,93,2015-01-16,11:37:00,6410887.7,744 12TH ST,1834090.7,FRHT,NaN,00600,4250685434,NaN,80.56E4+,RED ZONE
499971,56,PA,GY,58,2015-01-16,12:47:00,6479980.6,1224 OLYMPIC BLVD,1839651.3,FORD,NaN,00600,4250685445,NaN,80.69C,PARKED OVER TIME LIM
499972,56,PA,BK,58,2015-01-16,12:52:00,6416051.1,1400 OLYMPIC BLVD,1829910.4,LEXS,NaN,00600,4250685456,NaN,80.69C,PARKED OVER TIME LIM
499973,56,PA,BK,58,2015-01-16,12:59:00,6415496.3,1211 OLYMPIC BLVD,1829372,FORD,NaN,00600,4250685460,NaN,80.69C,PARKED OVER TIME LIM
499974,56,PA,BK,63,2015-01-16,13:12:00,6484927.7,701 12TH ST E,1834742.1,NISS,ED219,00600,4250685471,NaN,88.13B+,METER EXP.
499975,56,PA,GY,63,2015-01-16,15:06:00,6502799,201 12TH ST W,1742891.1,LINC,CB4319,00600,4250685493,NaN,88.13B+,METER EXP.
499976,56,PA,GY,63,2015-01-16,15:15:00,6504124.6,300 14TH ST E,1743768.1,FORD,CB2049,00600,4250685504,NaN,88.13B+,METER EXP.
499977,56,PA,GY,63,2015-01-16,15:21:00,6482449.1,1401 MAIN ST S,1835213.1,LEXS,CB348,00600,4250685515,NaN,88.13B+,METER EXP.
499978,56,PA,GY,63,2015-01-16,15:34:00,6485961.1,900 12TH ST E,1834155.2,TOYT,ED279,00600,4250685526,NaN,88.13B+,METER EXP.
499979,56,PA,GY,63,2015-01-16,15:58:00,6487821.1,301 WALL ST S,1839930.1,NISS,LT302,00600,4250685530,NaN,88.13B+,METER EXP.
499980,56,TK,WT,68,2015-01-16,16:05:00,6417115.2,843 MAPLE ST,1825539.9,GRUM,NaN,00600,4250685541,NaN,22500H,DOUBLE PARKING
499981,56,TK,BN,93,2015-01-16,16:08:00,6414698.9,950 OLYMPIC BLVD,1828648,FRHT,NaN,00600,4250685552,NaN,80.69AP+,NO STOP/STANDING
499982,56,PA,BK,63,2015-01-16,16:13:00,6483701.7,1201 SANTEE ST S,1835694,CADI,CB839,00600,4250685563,NaN,88.13B+,METER EXP.
499983,56,PA,BK,63,2015-01-16,17:11:00,6458410,1400 MAPLE AVE S,1762259.9,HOND,CB2075,00600,4250685574,NaN,88.13B+,METER EXP.
499984,56,PA,BL,58,2015-01-16,17:16:00,6485354.6,900 WALL ST S,1836571.8,TOYT,CB637,00600,4250685585,NaN,88.03A,OUTSIDE LINES/METER
499985,56,CM,WT,93,2015-01-02,12:59:00,99999,1438 EASTLAKE AVE,99999,FORD,NaN,00632,4250686016,NaN,80.56E4+,RED ZONE
499986,56,PA,GN,25,2015-01-02,13:18:00,99999,2007 N ALTA ST,99999,TOYT,NaN,00632,4250686020,NaN,5204A-,DISPLAY OF TABS
499987,56,PA,SL,63,2015-01-02,14:41:00,6498857.8,1300 BIGGY ST,1844506.4,HOND,MD322,00632,4250686031,NaN,88.13B+,METER EXP.
499988,56,PA,WT,93,2015-01-02,15:05:00,6490237.8,200 COLLEGE ST W,1845602.8,HOND,NaN,00632,4250686042,NaN,80.69A+,STOP/STAND PROHIBIT
499989,56,PA,WT,25,2015-01-02,15:05:00,6490237.8,200 COLLEGE ST W,1845602.8,HOND,NaN,00632,4250686053,NaN,5200,DISPLAY OF PLATES
499990,56,PA,BK,25,2015-01-02,15:16:00,6491170.5,901 AVILA ST,1843215.5,CHRY,NaN,00632,4250686064,NaN,5204A-,DISPLAY OF TABS
499991,56,CM,BN,93,2015-01-02,15:49:00,6490797.9,1261 PALMETTO ST,1837139,OTHR,NaN,00632,4250686075,NaN,80.56E4+,RED ZONE
499992,56,PA,WT,58,2015-01-02,16:23:00,6498857.8,1300 BIGGY ST,1844506.4,NISS,MD319,00632,4250686086,NaN,88.03A,OUTSIDE LINES/METER
499993,56,PA,SL,93,2015-01-02,16:45:00,6495106.6,325 BOYLE AVE S,1838751.6,FORD,NaN,00632,4250686090,NaN,80.56E4+,RED ZONE
499994,56,PA,BK,63,2015-01-05,13:16:00,6524824,821 MAPLE AVE S,1822642.1,TOYT,CB717,00681,4250686425,NaN,88.13B+,METER EXP.
499995,56,PA,GY,63,2015-01-05,13:36:00,6640079.3,951 TOWNE AVE S,1841186.2,TOYT,ED651A,00681,4250686436,NaN,88.13B+,METER EXP.
499996,56,PA,GY,63,2015-01-05,13:40:00,6505990.5,777 10TH ST E,1741998.2,CHEV,ED658,00681,4250686440,NaN,88.13B+,METER EXP.
499997,56,PA,RD,63,2015-01-05,13:49:00,6484589.5,1122 WALL ST S,1835634.7,HOND,CB2180A,00681,4250686451,NaN,88.13B+,METER EXP.
499998,56,PA,BK,58,2015-01-05,13:52:00,6484302.6,1202 WALL ST S,1835206.4,PONT,CB2162,00681,4250686462,NaN,88.03A,OUTSIDE LINES/METER
499999,56,PA,BK,25,2015-01-05,13:54:00,6484302.6,1202 WALL ST S,1835206.4,PONT,NaN,00681,4250686473,NaN,5204A-,DISPLAY OF TABS

In [18]:
# create unique number for csv file name based on the api_responses list
files_list = files[0:1]
z = [i.split('.', 1)[0] for i in files_list]
csv_number = z[0]

def missing_lat_long_processing():
    
    # save latitude with 99999 values into a separate csv file for later processing    
    parking_citations_lat_long_na = transformed_df[transformed_df["latitude"]=="99999"]
    parking_citations_lat_long_na.to_csv(f"missed_lat_long_{csv_number}.csv", encoding='utf-8', index=False)
    print ("Missing latitude/longitude data extracted")
    print("========================================================")


    shutil.move(f"missed_lat_long_{csv_number}.csv", 'data/missed_lat_long_db_ready')
    print("CSV file "f"missed_lat_long_{csv_number}.csv moved")
    
missing_lat_long_processing()

Missing latitude/longitude data extracted
========================================================
CSV file missed_lat_long_0000000002.csv moved

In [19]:
# drop parking tickets with latitude / longitude values of 99999.0
db_ready_df = transformed_df[transformed_df["latitude"] != "99999"]

In [20]:
# assign coordinate transformation engine
pm = '+proj=lcc +lat_1=34.03333333333333 +lat_2=35.46666666666667 +lat_0=33.5 +lon_0=-118 +x_0=2000000 ' \
     '+y_0=500000.0000000002 +ellps=GRS80 +datum=NAD83 +to_meter=0.3048006096012192 +no_defs'

# convert latitude and longitude to geographic coordinates
x_in,y_in = db_ready_df['latitude'].values, db_ready_df['longitude'].values
db_ready_df['latitude'],db_ready_df['longitude'] = transform(Proj(pm, preserve_units = True), Proj("+init=epsg:4326"), x_in,y_in)

/Users/pavelaltukhov/anaconda3/envs/PythonProjects/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

In [11]:
# convert fine_amount and agency columns to numerical format
# usage of "pandas.to_numeric" function convert to float data type

cols = ['fine_amount', 'agency']
db_ready_df[cols] = db_ready_df[cols].apply(pd.to_numeric, errors='coerce', axis=1)

/Users/pavelaltukhov/anaconda3/envs/PythonProjects/lib/python3.7/site-packages/pandas/core/frame.py:3391: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[k1] = value[k2]

In [67]:
# convert "ticket_number" column to integer datatype
db_ready_df["ticket_number"]=db_ready_df["ticket_number"].astype(int)

/Users/pavelaltukhov/anaconda3/envs/PythonProjects/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [22]:
def data_type_conversion():

    # convert fine_amount and agency columns to numerical format
    # usage of "pandas.to_numeric" function convert to float data type
    cols = ['fine_amount', 'agency']
    db_ready_df[cols] = db_ready_df[cols].apply(pd.to_numeric, errors='coerce', axis=1)
    
    return db_ready_df.info()

data_type_conversion()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 389547 entries, 0 to 499999
Data columns (total 16 columns):
agency                   389547 non-null float64
body_style               389406 non-null object
color                    389489 non-null object
fine_amount              389450 non-null float64
issue_date               389547 non-null datetime64[ns]
issue_time               389491 non-null object
latitude                 389547 non-null float64
location                 389547 non-null object
longitude                389547 non-null float64
make                     389361 non-null object
meter_id                 125223 non-null object
route                    388426 non-null object
ticket_number            389547 non-null object
vin                      15016 non-null object
violation_code           389547 non-null object
violation_description    389535 non-null object
dtypes: datetime64[ns](1), float64(4), object(11)
memory usage: 50.5+ MB

In [23]:
db_ready_df

,agency,body_style,color,fine_amount,issue_date,issue_time,latitude,location,longitude,make,meter_id,route,ticket_number,vin,violation_code,violation_description
0,54.0,PA,GY,73.0,2016-03-14,08:25:00,-118.368958,104 HARPER AVE S,34.074236,AUDI,NaN,00474,4278367181,NaN,80.69BS,NO PARK/STREET CLEAN
1,54.0,PA,GN,73.0,2016-03-14,08:27:00,-118.368958,112 HARPER AVE S,34.074167,TOYT,NaN,00474,4278367192,NaN,80.69BS,NO PARK/STREET CLEAN
2,54.0,PA,BK,73.0,2016-03-14,08:30:00,-118.368958,150 HARPER AVE S,34.073836,LEXS,NaN,00474,4278367203,NaN,80.69BS,NO PARK/STREET CLEAN
3,54.0,PA,BK,73.0,2016-03-14,08:31:00,-118.368958,150 HARPER AVE S,34.073836,VOLK,NaN,00474,4278367214,NaN,80.69BS,NO PARK/STREET CLEAN
4,54.0,PA,GY,73.0,2016-03-14,08:33:00,-118.368958,150 HARPER AVE S,34.073836,AUDI,NaN,00474,4278367225,NaN,80.69BS,NO PARK/STREET CLEAN
5,54.0,PA,BK,73.0,2016-03-14,09:06:00,-118.373206,320 ORLANDO AVE S,34.072627,ACUR,NaN,00474,4278367236,NaN,80.69BS,NO PARK/STREET CLEAN
6,54.0,PA,SL,73.0,2016-03-14,09:07:00,-118.373206,320 ORLANDO AVE S,34.072627,HOND,NaN,00474,4278367240,NaN,80.69BS,NO PARK/STREET CLEAN
7,54.0,PA,WT,73.0,2016-03-14,09:10:00,-118.370183,361 SWEETZER AVE S,34.071562,MERZ,NaN,00474,4278367251,NaN,80.69BS,NO PARK/STREET CLEAN
9,54.0,PA,GY,73.0,2016-03-14,09:16:00,-118.367956,316 LA JOLLA AVE S,34.076419,HOND,NaN,00474,4278367273,NaN,80.69BS,NO PARK/STREET CLEAN
11,54.0,PA,BK,73.0,2016-03-14,09:21:00,-118.366627,8142 W BLACKBURN AVE,34.071337,MAZD,NaN,00474,4278367295,NaN,80.69BS,NO PARK/STREET CLEAN
15,54.0,PA,GY,73.0,2016-03-14,09:35:00,-118.369400,6566 COLGATE AVE W,34.069959,TOYT,NaN,00474,4278367332,NaN,80.69BS,NO PARK/STREET CLEAN
16,54.0,PA,GY,25.0,2016-03-14,09:36:00,-118.369400,6566 COLGATE AVE W,34.069959,TOYT,NaN,00474,4278367343,NaN,5200,DISPLAY OF PLATES
17,54.0,PA,SL,73.0,2016-03-14,09:38:00,-118.369079,6556 COLGATE AVE W,34.069922,CHRY,NaN,00474,4278367354,NaN,80.69BS,NO PARK/STREET CLEAN
18,54.0,PA,RD,73.0,2016-03-14,09:39:00,-118.368758,6546 COLGATE AVE W,34.069886,CHEV,NaN,00474,4278367365,NaN,80.69BS,NO PARK/STREET CLEAN
20,54.0,PA,PR,73.0,2016-03-14,09:52:00,-118.372842,6670 LINDENHURST AVE W,34.067018,HOND,NaN,00474,4278367380,NaN,80.69BS,NO PARK/STREET CLEAN
21,54.0,PA,BK,73.0,2016-03-14,09:54:00,-118.372842,6670 LINDENHURST AVE W,34.067018,HYUN,NaN,00474,4278367391,NaN,80.69BS,NO PARK/STREET CLEAN
22,54.0,PA,GY,73.0,2016-03-14,09:55:00,-118.372842,6670 LINDENHURST AVE W,34.067018,TOYT,NaN,00474,4278367402,NaN,80.69BS,NO PARK/STREET CLEAN
23,54.0,PA,GY,25.0,2016-03-14,09:56:00,-118.372842,6670 LINDENHURST AVE W,34.067018,TOYT,NaN,00474,4278367413,NaN,5204A-,DISPLAY OF TABS
26,54.0,PA,MR,73.0,2016-03-14,12:17:00,-118.326606,5900 W WARING AVE,34.085297,KIA,NaN,00474,4278367446,NaN,80.69BS,NO PARK/STREET CLEAN
28,54.0,PA,BK,73.0,2016-03-14,12:24:00,-118.327708,727 N LILLIAN WAY,34.083963,HOND,NaN,00474,4278367461,NaN,80.69BS,NO PARK/STREET CLEAN
29,54.0,PA,BK,25.0,2016-03-14,12:25:00,-118.327708,727 N LILLIAN WAY,34.083963,HOND,NaN,00474,4278367472,NaN,5204A-,DISPLAY OF TABS
34,54.0,PA,WT,73.0,2016-03-14,12:43:00,-118.330978,6500 W ROMAINE ST,34.088922,RROV,NaN,00474,4278367520,NaN,80.69BS,NO PARK/STREET CLEAN
35,54.0,PA,BK,73.0,2016-03-15,08:06:00,-118.362620,111 HAYWORTH AVE S,34.074390,VOLK,NaN,00474,4278367531,NaN,80.69BS,NO PARK/STREET CLEAN
36,54.0,PA,WT,73.0,2016-03-15,08:08:00,-118.362621,133 HAYWORTH AVE S,34.074590,HYUN,NaN,00474,4278367542,NaN,80.69BS,NO PARK/STREET CLEAN
37,54.0,PA,GY,73.0,2016-03-15,08:10:00,-118.362622,153 HAYWORTH AVE S,34.074772,TOYT,NaN,00474,4278367553,NaN,80.69BS,NO PARK/STREET CLEAN
38,54.0,PA,WT,73.0,2016-03-15,08:12:00,-118.362622,165 HAYWORTH AVE S,34.074881,HOND,NaN,00474,4278367564,NaN,80.69BS,NO PARK/STREET CLEAN
39,54.0,PA,BK,73.0,2016-03-15,08:15:00,-118.363692,132 EDINBURGH AVE N,34.074585,LEXS,NaN,00474,4278367575,NaN,80.69BS,NO PARK/STREET CLEAN
40,54.0,PU,RD,73.0,2016-03-15,08:17:00,-118.364752,109 LAUREL AVE N,34.074362,TOYT,NaN,00474,4278367586,NaN,80.69BS,NO PARK/STREET CLEAN
41,54.0,PA,BK,73.0,2016-03-15,08:21:00,-118.364752,101 LAUREL AVE S,34.074289,FORD,NaN,00474,4278367590,NaN,80.69BS,NO PARK/STREET CLEAN
42,54.0,PA,BK,73.0,2016-03-15,08:24:00,-118.366884,161 KILKEA DR S,34.074826,MAZD,NaN,00474,4278367601,NaN,80.69BS,NO PARK/STREET CLEAN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499968,56.0,TK,BN,93.0,2015-01-15,17:26:00,-118.388546,600 2ND ST,33.856941,FRHT,NaN,00600,4250685412,NaN,80.56E4+,RED ZONE
499969,56.0,PA,SL,63.0,2015-01-16,10:40:00,-118.236090,201 HEWITT ST S,34.047132,FORD,AE136,00600,4250685423,NaN,88.13B+,METER EXP.
499970,56.0,TK,BN,93.0,2015-01-16,11:37:00,-118.497641,744 12TH ST,34.031148,FRHT,NaN,00600,4250685434,NaN,80.56E4+,RED ZONE
499971,56.0,PA,GY,58.0,2015-01-16,12:47:00,-118.269653,1224 OLYMPIC BLVD,34.047152,FORD,NaN,00600,4250685445,NaN,80.69C,PARKED OVER TIME LIM
499972,56.0,PA,BK,58.0,2015-01-16,12:52:00,-118.480534,1400 OLYMPIC BLVD,34.019730,LEXS,NaN,00600,4250685456,NaN,80.69C,PARKED OVER TIME LIM
499973,56.0,PA,BK,58.0,2015-01-16,12:59:00,-118.482356,1211 OLYMPIC BLVD,34.018243,FORD,NaN,00600,4250685460,NaN,80.69C,PARKED OVER TIME LIM
499974,56.0,PA,BK,63.0,2015-01-16,13:12:00,-118.253281,701 12TH ST E,34.033698,NISS,ED219,00600,4250685471,NaN,88.13B+,METER EXP.
499975,56.0,PA,GY,63.0,2015-01-16,15:06:00,-118.193712,201 12TH ST W,33.781417,LINC,CB4319,00600,4250685493,NaN,88.13B+,METER EXP.
499976,56.0,PA,GY,63.0,2015-01-16,15:15:00,-118.189356,300 14TH ST E,33.783833,FORD,CB2049,00600,4250685504,NaN,88.13B+,METER EXP.
499977,56.0,PA,GY,63.0,2015-01-16,15:21:00,-118.261466,1401 MAIN ST S,34.034975,LEXS,CB348,00600,4250685515,NaN,88.13B+,METER EXP.
499978,56.0,PA,GY,63.0,2015-01-16,15:34:00,-118.249866,900 12TH ST E,34.032092,TOYT,ED279,00600,4250685526,NaN,88.13B+,METER EXP.
499979,56.0,PA,GY,63.0,2015-01-16,15:58:00,-118.243773,301 WALL ST S,34.047973,NISS,LT302,00600,4250685530,NaN,88.13B+,METER EXP.
499980,56.0,TK,WT,68.0,2015-01-16,16:05:00,-118.476954,843 MAPLE ST,34.007735,GRUM,NaN,00600,4250685541,NaN,22500H,DOUBLE PARKING
499981,56.0,TK,BN,93.0,2015-01-16,16:08:00,-118.484976,950 OLYMPIC BLVD,34.016243,FRHT,NaN,00600,4250685552,NaN,80.69AP+,NO STOP/STANDING
499982,56.0,PA,BK,63.0,2015-01-16,16:13:00,-118.257336,1201 SANTEE ST S,34.036305,CADI,CB839,00600,4250685563,NaN,88.13B+,METER EXP.
499983,56.0,PA,BK,63.0,2015-01-16,17:11:00,-118.339995,1400 MAPLE AVE S,33.834314,HOND,CB2075,00600,4250685574,NaN,88.13B+,METER EXP.
499984,56.0,PA,BL,58.0,2015-01-16,17:16:00,-118.251888,900 WALL ST S,34.038728,TOYT,CB637,00600,4250685585,NaN,88.03A,OUTSIDE LINES/METER
499987,56.0,PA,SL,63.0,2015-01-02,14:41:00,-118.207371,1300 BIGGY ST,34.060616,HOND,MD322,00632,4250686031,NaN,88.13B+,METER EXP.
499988,56.0,PA,WT,93.0,2015-01-02,15:05:00,-118.235839,200 COLLEGE ST W,34.063577,HOND,NaN,00632,4250686042,NaN,80.69A+,STOP/STAND PROHIBIT
499989,56.0,PA,WT,25.0,2015-01-02,15:05:00,-118.235839,200 COLLEGE ST W,34.063577,HOND,NaN,00632,4250686053,NaN,5200,DISPLAY OF PLATES
499990,56.0,PA,BK,25.0,2015-01-02,15:16:00,-118.232742,901 AVILA ST,34.057023,CHRY,NaN,00632,4250686064,NaN,5204A-,DISPLAY OF TABS
499991,56.0,CM,BN,93.0,2015-01-02,15:49:00,-118.233925,1261 PALMETTO ST,34.040323,OTHR,NaN,00632,4250686075,NaN,80.56E4+,RED ZONE
499992,56.0,PA,WT,58.0,2015-01-02,16:23:00,-118.207371,1300 BIGGY ST,34.060616,NISS,MD319,00632,4250686086,NaN,88.03A,OUTSIDE LINES/METER
499993,56.0,PA,SL,93.0,2015-01-02,16:45:00,-118.219714,325 BOYLE AVE S,34.044781,FORD,NaN,00632,4250686090,NaN,80.56E4+,RED ZONE
499994,56.0,PA,BK,63.0,2015-01-05,13:16:00,-118.121553,821 MAPLE AVE S,34.000653,TOYT,CB717,00681,4250686425,NaN,88.13B+,METER EXP.
499995,56.0,PA,GY,63.0,2015-01-05,13:36:00,-117.741140,951 TOWNE AVE S,34.051393,TOYT,ED651A,00681,4250686436,NaN,88.13B+,METER EXP.
499996,56.0,PA,GY,63.0,2015-01-05,13:40:00,-118.183205,777 10TH ST E,33.778979,CHEV,ED658,00681,4250686440,NaN,88.13B+,METER EXP.
499997,56.0,PA,RD,63.0,2015-01-05,13:49:00,-118.254405,1122 WALL ST S,34.036148,HOND,CB2180A,00681,4250686451,NaN,88.13B+,METER EXP.
499998,56.0,PA,BK,58.0,2015-01-05,13:52:00,-118.255349,1202 WALL ST S,34.034969,PONT,CB2162,00681,4250686462,NaN,88.03A,OUTSIDE LINES/METER
499999,56.0,PA,BK,25.0,2015-01-05,13:54:00,-118.255349,1202 WALL ST S,34.034969,PONT,NaN,00681,4250686473,NaN,5204A-,DISPLAY OF TABS

In [24]:
db_ready_df.to_csv(f"citations_{csv_number}.csv", encoding = 'utf-8', index = False)
shutil.move(f"citations_{csv_number}.csv", 'data/citations_db_ready')

'data/citations_db_ready/citations_0000000002.csv'